name: Unit Tests Run
on:
  pull_request:
    branches:
      - '**'
jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    environment: testing
    services:
      mongodb:
        image: mongo:7.0.16
        ports:
          - 27017:27017
        env:
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: 4dm1n
          MONGO_INITDB_DATABASE: ${{ vars.CI_MONGO_INITDB_DATABASE }}
        options: >-
          --health-cmd "mongosh --quiet --eval 'db.runCommand({ ping: 1 }).ok'"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      redis:
        image: redis:7.4.2
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli --raw incr ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - name: Make envfile
        uses: SpicyPizza/create-envfile@v2.0
        with:
          envkey_ENVIRONMENT: "development"
          envkey_DATABASE_TECHNOLOGY: mongoDB
          envkey_MONGO_PROTOCOL: mongodb
          envkey_MONGO_HOST: ${{vars.CI_MONGO_HOST}}
          envkey_MONGO_PORT: 27017
          envkey_MONGO_INITDB_DATABASE: ${{vars.CI_MONGO_INITDB_DATABASE}}
          envkey_MONGO_INITDB_ROOT_USERNAME: root
          envkey_MONGO_INITDB_ROOT_PASSWORD: 4dm1n
          envkey_DATABASE_NAME: ${{vars.CI_MONGO_INITDB_DATABASE}}
          envkey_DATABASE_USERNAME: ${{vars.CI_DATABASE_USERNAME}}
          envkey_DATABASE_PASSWORD: ${{vars.CI_DATABASE_PASSWORD}}
          envkey_SERVER_PORT: ${{vars.CI_SERVER_PORT}}
          envkey_AVATARS_FOLDER: ${{vars.CI_AVATARS_FOLDER}}
          envkey_ORG_AVATARS_FOLDER: ${{vars.CI_ORG_AVATARS_FOLDER}}
          envkey_COLLECTIONS_FOLDER: ${{vars.CI_COLLECTIONS_FOLDER}}
          envkey_SERVER_STATICS_FOLDER: public/
          envkey_REDIS_URL: ${{vars.CI_REDIS_URL}}
          directory: ./api
          file_name: .env
          fail_on_empty: false
          sort_keys: false

      - name: Install mongosh
        run: |
          sudo apt-get install gnupg curl
          curl -fsSL https://pgp.mongodb.com/server-8.0.asc | \
          sudo gpg -o /usr/share/keyrings/mongodb-server-8.0.gpg \
          --dearmor
          echo "deb [ arch=amd64,arm64 signed-by=/usr/share/keyrings/mongodb-server-8.0.gpg ] https://repo.mongodb.org/apt/ubuntu noble/mongodb-org/8.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-8.0.list
          sudo apt-get update
          sudo apt-get install -y mongodb-mongosh
          sudo apt-get install -y minizinc
          sudo apt-get clean

      - name: Initialize MongoDB user
        run: |
          mongosh "mongodb://root:4dm1n@localhost:27017/admin" --eval '
            db = db.getSiblingDB("${{ vars.CI_MONGO_INITDB_DATABASE }}");
            db.createUser({
              user: "${{ vars.CI_DATABASE_USERNAME }}",
              pwd: "${{ vars.CI_DATABASE_PASSWORD }}",
              roles: [
                { role: "readWrite", db: "${{ vars.CI_MONGO_INITDB_DATABASE }}" },
                { role: "dbAdmin", db: "${{ vars.CI_MONGO_INITDB_DATABASE }}" }
              ]
            });
            db = db.getSiblingDB("ican_test_db");
            db.createUser({
              user: "${{ vars.CI_DATABASE_USERNAME }}",
              pwd: "${{ vars.CI_DATABASE_PASSWORD }}",
              roles: [
                { role: "readWrite", db: "ican_test_db" },
                { role: "dbAdmin", db: "ican_test_db" }
              ]
            });
          '

      - name: Install MiniZinc (Official Bundle)
        run: |
          sudo apt-get update
          sudo apt-get install -y snapd
          sudo snap install minizinc --classic
          
      - name: Verify MiniZinc and Solvers
        run: |
          minizinc --version
          minizinc --solvers # Esto es clave: si no sale 'gecode', por eso te da el 500

      - name: Install pnpm
        run: npm install -g pnpm
      
      - name: Install dependencies
        run: pnpm install

      - name: Run tests
        run: pnpm run test
